# Generated by Django 4.2.7 on 2024-08-20 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0003_remove_publishedarticle_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('selectors', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='article_link',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='rephrased_article',
        ),
        migrations.RemoveField(
            model_name='publishedarticle',
            name='title',
        ),
        migrations.AddField(
            model_name='publishedarticle',
            name='article',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='X.article'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_link', models.URLField(unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='X.scrapedcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_link', models.URLField(unique=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='X.category')),
            ],
        ),
    ]
