# Generated by Django 4.2.7 on 2024-08-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0004_scrapedcategory_websiteinput_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedArticle',
        ),
        migrations.DeleteModel(
            name='ScrapedCategory',
        ),
    ]
