# Generated by Django 4.2.7 on 2024-08-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0007_remove_publishedarticle_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedarticle',
            name='article_link',
            field=models.URLField(),
        ),
    ]
