# Generated by Django 4.2.7 on 2024-08-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedArticle',
        ),
        migrations.DeleteModel(
            name='ScrapedCategory',
        ),
    ]
