# Generated by Django 4.2.7 on 2024-08-20 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0002_delete_scrapedarticle_delete_scrapedcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_link', models.URLField(unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.scrapedcategory')),
            ],
        ),
    ]
