# Generated by Django 5.1 on 2024-08-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_taskprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
